version: 2

notify:
  webhooks:
    - url: https://hermes.data.security.rackspace.com/circle

jobs:
  install_dependencies_py2:
    working_directory: ~/repo
    docker:
      - image: circleci/python:2.7.15
    steps:
      - checkout
      - restore_cache:
          key: virtualenv-py2-v1-{{ checksum "requirements/tests.txt" }}-{{ checksum "requirements.txt" }}
      - attach_workspace:
          at: ~/repo
      - run:
          name: Install Python build dependencies
          command: |
            test -x venv/bin/activate || virtualenv venv
            . venv/bin/activate
            pip install tox
            pip install -U appdirs packaging six
            pip install -U pip setuptools virtualenv
            pip install -r requirements/tests.txt
      - persist_to_workspace:
          root: ~/repo
          paths: [venv]
      - save_cache:
          key: virtualenv-py2-v1-{{ checksum "requirements/tests.txt" }}-{{ checksum "requirements.txt" }}
          paths: [venv]
  test_py2:
    working_directory: ~/repo
    docker:
      - image: circleci/python:2.7.15
    steps:
      - checkout
      - restore_cache:
          key: tox-py2-v1-{{ checksum "requirements/tests.txt" }}-{{ checksum "requirements.txt" }}
      - attach_workspace:
          at: ~/repo
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            tox -v -e py27
      - save_cache:
          key: tox-py2-v1-{{ checksum "requirements/tests.txt" }}-{{ checksum "requirements.txt" }}
          paths: [.tox]

  install_dependencies_py3:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.6.6
    steps:
      - checkout
      - restore_cache:
          key: virtualenv-py3-v1-{{ checksum "requirements/tests.txt" }}-{{ checksum "requirements.txt" }}
      - attach_workspace:
          at: ~/repo
      - run:
          name: Install Python build dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install tox
            pip install -U appdirs packaging six
            pip install -U pip setuptools virtualenv
            pip install -r requirements/tests.txt
      - persist_to_workspace:
          root: ~/repo
          paths: [venv]
      - save_cache:
          key: virtualenv-py3-v1-{{ checksum "requirements/tests.txt" }}-{{ checksum "requirements.txt" }}
          paths: [venv]
  test_py3:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.6.6
    steps:
      - checkout
      - restore_cache:
          key: tox-py3-v1-{{ checksum "requirements/tests.txt" }}-{{ checksum "requirements.txt" }}
      - attach_workspace:
          at: ~/repo
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            tox -v -e py36
      - save_cache:
          key: tox-py3-v1-{{ checksum "requirements/tests.txt" }}-{{ checksum "requirements.txt" }}
          paths: [.tox]


workflows:
  version: 2
  test:
    jobs:
      - install_dependencies_py2
      - test_py2:
          requires: [install_dependencies_py2]

      - install_dependencies_py3
      - test_py3:
          requires: [install_dependencies_py3]
